### ISSUE TITLE
OnColorSelected callback is not working

### ISSUE THREAD

**Issue by nvko** [vadiole/colorpicker#1] opened 2021-06-27 01:07 UTC
hey, before anything - thanks for this awesome library! now my issue is that color selection listener works only after first click. if I want to select a new one, callback is not working, tried both ways:
```
colorPicker = ColorPickerDialog.Builder()
            .setInitialColor(Color.BLACK)
            .setButtonOkText(android.R.string.ok)
            .setButtonCancelText(android.R.string.cancel)
            .onColorSelected { color: Int ->
                note.color = color
                noteColorView.setBackgroundColor(color)
            }
            .create()
```
```
 colorPicker = ColorPickerDialog.Builder()
            .setInitialColor(Color.BLACK)
            .setButtonOkText(android.R.string.ok)
            .setButtonCancelText(android.R.string.cancel)
            .onColorSelected(onSelectColorListener)
            .create()
            
 private var onSelectColorListener: OnSelectColorListener = object : OnSelectColorListener {
        override fun onColorSelected(color: Int) {
            note.color = color
            noteColorView.setBackgroundColor(color)
        }
    }
```

am I doing something wrong or is it the library issue? sorry, I'm a Kotlin newbie :)

**Comment by vadiole** [comment] 2021-06-28 08:41
Hi, glad you like the library! 
Tell me, what do you mean by "works only after first click"?

**Comment by nvko** [comment] 2021-07-10 01:14
hi, thanks for the reply and sorry for my late response. i don't remember exactly what was it (since I had a deadline and had to change a library xD). if I remember correctly I set the color in a dialog and it worked perfectly fine. but when I opened a dialog again and tried to change a color then the callback wasn't called.

**Comment by Takachi67** [comment] 2021-10-30 19:04
Hi, same for me. After clicked "OK", color changed. But if I select another one and click again on "OK", onColorSelected isn't triggered.

**Comment by vadiole** [comment] 2021-10-30 19:49
> Hi, same for me. After clicked "OK", color changed. But if I select another one and click again on "OK", onColorSelected isn't triggered.

Hi! Thanks for your comment.
Could you share a minimal reproducible example, please?

**Comment by Takachi67** [comment] 2021-10-30 19:52
Just took the example from the "Usage" part.

**Comment by vadiole** [comment] 2021-10-30 20:54
> Just took the example from the "Usage" part.

You did something wrong. The example that is described in the readme works, you can download example.apk from releases and make sure with it.

**Comment by vadiole** [comment] 2021-10-30 21:05
> Just took the example from the "Usage" part.

Оr do you mean that you need to pull the slider at least once in order to return the value, otherwise no defaultColor is returned?

**Comment by vadiole** [comment] 2021-10-30 21:08
> Just took the example from the "Usage" part.

Make sure you create a dialog every time you need a picker.  You can see the full example here:

https://github.com/vadiole/colorpicker/blob/master/demo/src/main/java/vadiole/colorpickerdemo/MainActivity.kt#L53-L94

**Comment by Takachi67** [comment] 2021-10-31 06:59
Ok, I was calling the show method on click, not a new ColorPicker.

**Comment by vadiole** [comment] 2022-12-16 18:07
Not a bug, closing

**Closed as completed by vadiole** 2022-12-16 18:07 UTC
Labels: bug
